select e.lname from employee e, dependent d where d.sex='M' and e.ssn=d.essn group by e.lname  order by e.lname;
select sum(hours), pno from works_on, project where pno=pnumber and dnum=(select dnumber from department where dname='research') group by pno;
select year(current_date()) - year(bdate) as age from employee order by age asc;
select works_on.essn as essn, sum(hours) from works_on, (select essn from works_on group by essn having avg(hours) > 9) e where works_on.essn=e.essn group by works_on.essn;
select fname from employee e where e.salary > (select AVG(f.salary) from employee f where f.dno = e.dno) order by fname;
select fname from employee where fname like '%s%' or fname like '%S%' order by fname;
select fname, lname, salary from employee where salary > 24999 order by lname;
select distinct plocation from project order by plocation;
select fname, minit, lname, ssn, bdate, address, sex, salary, super_ssn, dno from employee where year(bdate) > 1950 and sex='M' order by salary;
select fname, lname, bdate, salary from employee where super_ssn is NULL or salary < 30000 order by bdate desc;
select fname, minit, lname, ssn, bdate, address, sex, salary, super_ssn, dno from employee where sex='F' and salary between 30000 and 50000;
select fname from employee where ssn not in (select essn from dependent) order by fname;
select min(salary) from employee, department where dno=dnumber;
select fname First from employee order by First;
select sex, sum(salary) from employee group by sex order by sex;
select count(*) from employee where dno=5;
select ssn, sum(hours) from employee left join works_on on ssn=essn group by ssn order by ssn;
select min(salary) from employee, department where dnumber=dno and dname='Administration';
select dno, count(ssn) from employee where salary > 30000 group by dno order by dno;
select essn from employee, dependent where essn=ssn group by essn having count(essn) > 1;
select essn, count(pno) from works_on group by essn having count(pno) > 1 order by essn;
select ssn, fname, dname from employee, department where dnumber=dno order by ssn;